from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

import pandas as pd


@dataclass
class InvestmentSignal:
    """
    Signal generated by WEMA5_INVESTMENT_v1.

    action:
        BUY
        SELL
        HOLD
    """

    action: str
    date: Optional[pd.Timestamp]
    price: Optional[float]
    williams_r: Optional[float]
    ma35: Optional[float]
    ema10: Optional[float]
    reason: str


class WEMA5InvestmentStrategy:
    """
    WEMA5_INVESTMENT_v1

    Investment / trend-following strategy.

    Entry:
        1. Williams %R(14) crosses upward through -55.
        2. Close > MA35.
        3. Close > EMA10.
        4. Entry is executed on the next day's open.

    Exit:
        1. Position is already open.
        2. Daily candle closes below MA35.
        3. Exit is executed on the next day's open.

    Important:
        Williams reaching -10/-11/-12/-9/-8 is NOT an exit.
    """

    NAME = "WEMA5_INVESTMENT_v1"

    WILLIAMS_PERIOD = 14
    MA_PERIOD = 35
    EMA_PERIOD = 10
    WILLIAMS_ENTRY_LEVEL = -55.0

    def __init__(
        self,
        williams_period: int = WILLIAMS_PERIOD,
        ma_period: int = MA_PERIOD,
        ema_period: int = EMA_PERIOD,
        williams_entry_level: float = WILLIAMS_ENTRY_LEVEL,
    ) -> None:
        self.williams_period = williams_period
        self.ma_period = ma_period
        self.ema_period = ema_period
        self.williams_entry_level = williams_entry_level

    def add_indicators(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Add indicators required by WEMA5_INVESTMENT_v1.

        Required columns:
            date
            open
            high
            low
            close
            volume
        """

        required = {
            "date",
            "open",
            "high",
            "low",
            "close",
            "volume",
        }

        missing = required - set(df.columns)

        if missing:
            raise ValueError(
                f"Missing required columns: {sorted(missing)}"
            )

        out = df.copy()

        out["date"] = pd.to_datetime(out["date"], errors="coerce")

        numeric_columns = [
            "open",
            "high",
            "low",
            "close",
            "volume",
        ]

        for column in numeric_columns:
            out[column] = pd.to_numeric(
                out[column],
                errors="coerce",
            )

        out = out.dropna(
            subset=[
                "date",
                "open",
                "high",
                "low",
                "close",
            ]
        )

        out = out.sort_values("date")
        out = out.drop_duplicates(
            subset=["date"],
            keep="last",
        )

        # ---------------------------------------------------------
        # Williams %R
        # ---------------------------------------------------------

        highest_high = (
            out["high"]
            .rolling(
                self.williams_period,
                min_periods=self.williams_period,
            )
            .max()
        )

        lowest_low = (
            out["low"]
            .rolling(
                self.williams_period,
                min_periods=self.williams_period,
            )
            .min()
        )

        denominator = highest_high - lowest_low

        denominator = denominator.replace(0, pd.NA)

        out["williams_r"] = (
            -100
            * (
                highest_high - out["close"]
            )
            / denominator
        )

        # ---------------------------------------------------------
        # MA35
        # ---------------------------------------------------------

        out["ma35"] = (
            out["close"]
            .rolling(
                self.ma_period,
                min_periods=self.ma_period,
            )
            .mean()
        )

        # ---------------------------------------------------------
        # EMA10
        # ---------------------------------------------------------

        out["ema10"] = (
            out["close"]
            .ewm(
                span=self.ema_period,
                adjust=False,
                min_periods=self.ema_period,
            )
            .mean()
        )

        # Previous Williams value
        out["williams_prev"] = out["williams_r"].shift(1)

        # Williams cross above -55
        out["williams_cross_up"] = (
            (out["williams_prev"] < self.williams_entry_level)
            & (
                out["williams_r"]
                >= self.williams_entry_level
            )
        )

        # Trend conditions
        out["close_above_ma35"] = (
            out["close"] > out["ma35"]
        )

        out["close_above_ema10"] = (
            out["close"] > out["ema10"]
        )

        # Complete entry condition
        out["entry_condition"] = (
            out["williams_cross_up"]
            & out["close_above_ma35"]
            & out["close_above_ema10"]
        )

        # Exit condition
        out["exit_condition"] = (
            out["close"] < out["ma35"]
        )

        return out

    def generate_signal(
        self,
        df: pd.DataFrame,
        in_position: bool = False,
    ) -> InvestmentSignal:
        """
        Evaluate the latest COMPLETED daily candle.

        This method does not execute an order.

        For a BUY signal:
            execute on the next day's OPEN.

        For a SELL signal:
            execute on the next day's OPEN.
        """

        if len(df) < max(
            self.williams_period,
            self.ma_period,
            self.ema_period,
        ) + 2:
            return InvestmentSignal(
                action="HOLD",
                date=None,
                price=None,
                williams_r=None,
                ma35=None,
                ema10=None,
                reason="Not enough candles",
            )

        data = self.add_indicators(df)

        row = data.iloc[-1]

        date = row["date"]

        close = float(row["close"])
        williams = row["williams_r"]
        ma35 = row["ma35"]
        ema10 = row["ema10"]

        if pd.isna(williams) or pd.isna(ma35) or pd.isna(ema10):
            return InvestmentSignal(
                action="HOLD",
                date=date,
                price=close,
                williams_r=(
                    None
                    if pd.isna(williams)
                    else float(williams)
                ),
                ma35=(
                    None
                    if pd.isna(ma35)
                    else float(ma35)
                ),
                ema10=(
                    None
                    if pd.isna(ema10)
                    else float(ema10)
                ),
                reason="Indicators not ready",
            )

        # ---------------------------------------------------------
        # EXIT
        # ---------------------------------------------------------

        if in_position and bool(row["exit_condition"]):
            return InvestmentSignal(
                action="SELL",
                date=date,
                price=close,
                williams_r=float(williams),
                ma35=float(ma35),
                ema10=float(ema10),
                reason=(
                    "Daily close below MA35"
                ),
            )

        # ---------------------------------------------------------
        # BUY
        # ---------------------------------------------------------

        if not in_position and bool(row["entry_condition"]):
            return InvestmentSignal(
                action="BUY",
                date=date,
                price=close,
                williams_r=float(williams),
                ma35=float(ma35),
                ema10=float(ema10),
                reason=(
                    "Williams crossed above -55; "
                    "close above MA35 and EMA10"
                ),
            )

        # ---------------------------------------------------------
        # HOLD
        # ---------------------------------------------------------

        if in_position:
            if close > float(ma35):
                reason = (
                    "HOLD — price remains above MA35"
                )
            else:
                reason = (
                    "HOLD — exit condition not confirmed"
                )
        else:
            reason = (
                "No investment entry condition"
            )

        return InvestmentSignal(
            action="HOLD",
            date=date,
            price=close,
            williams_r=float(williams),
            ma35=float(ma35),
            ema10=float(ema10),
            reason=reason,
        )